services:
  - type: web
    name: proyecto-soda-bambu
    env: php
    region: oregon
    plan: free
    rootDir: source_code  # <--- CAMBIA ESTO por el nombre de tu subcarpeta
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache
    startCommand: composer run dev
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: true
