<?php

namespace App\Models;

use Database\Factories\ContractFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Contract extends Model
{
    /** @use HasFactory<ContractFactory> */
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'user_id',
        'business_name',
        'start_date',
        'end_date',
        'days_to_serve',
        'portions_per_day',
        'total_value',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'start_date' => 'date',
            'end_date' => 'date',
            'days_to_serve' => 'array', // Transform JSON to array and vice versa
            'total_value' => 'integer',
        ];
    }

    /**
     * Relation: Generated by User.
     * A contract belongs to a single user who processed it.
     *
     * @return BelongsTo<User, Contract>
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Relation: Contract Details.
     * A contract can have multiple details (products, meal times, etc.).
     *
     * @return HasMany<ContractDetail>
     */
    public function details()
    {
        return $this->hasMany(ContractDetail::class);
    }

    /**
     * Relation: Payments.
     * A contract can have multiple payments (e.g., split payments).
     *
     * @return MorphMany<Payment>
     */
    public function payments(): MorphMany
    {
        return $this->morphMany(Payment::class, 'origin');
    }
}
