<?php

namespace App\Models;

use Database\Factories\ContractFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Contract extends Model
{
    /** @use HasFactory<ContractFactory> */
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'user_id',
        'client_id',
        'business_name',
        'start_date',
        'end_date',
        'days_to_serve',
        'portions_per_day',
        'total_value',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'start_date' => 'date',
        'end_date' => 'date',
        'days_to_serve' => 'array',
        'portions_per_day' => 'integer',
        'total_value' => 'integer',
    ];

    /**
     * Accesor for dynamic contract status based on dates and deletion state.
     *
     * @return string Contract status: 'upcoming', 'active', 'expired', or 'inactive'
     */
    public function getStatusAttribute(): string
    {
        if ($this->deleted_at) {
            return 'inactive';
        }
        $today = now()->startOfDay();
        if ($today->lt($this->start_date)) {
            return 'upcoming';
        }
        if ($today->gt($this->end_date)) {
            return 'expired';
        }

        return 'active';
    }

    /**
     * Get the contract period as a formatted date range.
     *
     * @return string Formatted period or 'Undefined' when dates are missing.
     */
    public function getPeriodAttribute(): string
    {
        if ($this->start_date && $this->end_date) {
            return $this->start_date->locale('es')->format('d M Y').' - '.$this->end_date->locale('es')->format('d M Y');
        }

        return 'No definido';
    }

    /**
     * Relation: Generated by User.
     * A contract belongs to a single user who processed it.
     *
     * @return BelongsTo<User, Contract>
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Relation: Associated Client.
     * A contract belongs to a single client.
     *
     * @return BelongsTo<Client, Contract>
     */
    public function client(): BelongsTo
    {
        return $this->belongsTo(Client::class);
    }

    /**
     * Relation: Contract Details.
     * A contract can have multiple details (products, meal times, etc.).
     *
     * @return HasMany<ContractDetail>
     */
    public function details()
    {
        return $this->hasMany(ContractDetail::class);
    }

    /**
     * Relation: Payments.
     * A contract can have multiple payments (e.g., split payments).
     *
     * @return MorphMany<Payment>
     */
    public function payments(): MorphMany
    {
        return $this->morphMany(Payment::class, 'origin');
    }
}
