<?php

namespace App\Models;

use App\Contracts\Receipable;
use App\Enums\ContractState;
use Carbon\Carbon;
use Database\Factories\ContractFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Contract extends Model implements Receipable
{
    /** @use HasFactory<ContractFactory> */
    use HasFactory, SoftDeletes;

    /**
     * Cache for receipt items to avoid redundant calculations during a single request lifecycle.
     * @var array|null
     */
    private ?array $receiptItemsCache = null;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'user_id',
        'client_id',
        'business_name',
        'start_date',
        'end_date',
        'days_to_serve',
        'portions_per_day',
        'total_value',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'start_date' => 'date',
        'end_date' => 'date',
        'days_to_serve' => 'array',
        'portions_per_day' => 'integer',
        'total_value' => 'integer',
    ];

    /**
     * Accesor for dynamic contract status based on dates and deletion state.
     *
     * @return string Contract status: 'upcoming', 'active', 'expired', or 'inactive'
     */
    public function getStatusAttribute(): string
    {
        if ($this->deleted_at) {
            return ContractState::INACTIVE->value;
        }
        $today = now()->startOfDay();
        if ($today->lt($this->start_date)) {
            return ContractState::UPCOMING->value;
        }
        if ($today->gt($this->end_date)) {
            return ContractState::EXPIRED->value;
        }

        return ContractState::ACTIVE->value;
    }

    /**
     * Get the contract period as a formatted date range.
     *
     * @return string Formatted period or 'Undefined' when dates are missing.
     */
    public function getPeriodAttribute(): string
    {
        if ($this->start_date && $this->end_date) {
            $start = Carbon::parse($this->start_date)->locale('es')->isoFormat('D MMM YYYY');
            $end = Carbon::parse($this->end_date)->locale('es')->isoFormat('D MMM YYYY');

            return "$start - $end";
        }

        return 'No definido';
    }

    /**
     * Relation: Generated by User.
     * A contract belongs to a single user who processed it.
     *
     * @return BelongsTo<User, Contract>
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Relation: Associated Client.
     * A contract belongs to a single client.
     *
     * @return BelongsTo<Client, Contract>
     */
    public function client(): BelongsTo
    {
        return $this->belongsTo(Client::class);
    }

    /**
     * Relation: Contract Details.
     * A contract can have multiple details (products, meal times, etc.).
     *
     * @return HasMany<ContractDetail>
     */
    public function details()
    {
        return $this->hasMany(ContractDetail::class);
    }

    /**
     * Relation: Payments.
     * A contract can have multiple payments (e.g., split payments).
     *
     * @return MorphMany<Payment>
     */
    public function payments(): MorphMany
    {
        return $this->morphMany(Payment::class, 'origin');
    }

    // ===== Receipable Interface Implementation =====

    /**
     * Get the receipt/invoice number for this contract.
     */
    public function getReceiptNumber(): string
    {
        $contractId = str_pad($this->id, 10, '0', STR_PAD_LEFT);
        return "CONTRATO-{$contractId}";
    }

    /**
     * Get the date when this contract was created (for receipt purposes).
     */
    public function getReceiptDate(): Carbon
    {
        return $this->created_at ?? now();
    }

    /**
     * Get the contract details as receipt items.
     */
    public function getReceiptItems(): array
    {
        if ($this->receiptItemsCache !== null) {
            return $this->receiptItemsCache;
        }

        $results = $this->details->groupBy('product_id')->map(function ($group) {
            $firstDetail = $group->first();
            $product = $firstDetail->product;

            // Handle case where product might have been deleted after contract creation
            if (!$product) {
                return [
                    'name' => "Producto #{$firstDetail->product_id}",
                    'quantity' => $group->count(),
                    'unit_price' => 0,
                    'sub_total' => 0,
                    'applied_tax' => 0,
                ];
            }

            // Count total quantity for this product across all contract details
            $quantity = $group->count() * $firstDetail->contract->portions_per_day;

            // Use the product's sale price as the unit price for receipt purposes
            $unitPrice = $product->sale_price;

            // Subtotal (base_price sum for all quantities)
            $subTotal = $quantity * $unitPrice;

            return [
                'name' => $product->name,
                'quantity' => $quantity,
                'unit_price' => (int) $unitPrice,
                'sub_total' => (int) $subTotal,
                'applied_tax' => 0, // No tax applied for now, but can be calculated if needed
            ];
        })->values()->toArray();
        
        $this->receiptItemsCache = $results;
        return $results;
    }

    /**
     * Get the payments associated with this contract.
     */
    public function getReceiptPayments(): array
    {
        return $this->payments()->get()->map(fn($payment) => [
            'amount' => $payment->amount,
            'method_label' => $payment->method->label(),
            'change_amount' => $payment->change_amount,
            'reference' => $payment->reference,
            'date' => $payment->created_at,
        ])->toArray();
    }

    /**
     * Get the total tax amount for all contract details.
     */
    public function getReceiptTaxTotal(): int
    {
        // Since getReceiptItems already calculates the tax amount in 'applied_tax', 
        // we just need to sum it up.
        return collect($this->getReceiptItems())->sum('applied_tax');
    }

    /**
     * Get the contract subtotal (sum of all details before tax).
     */
    public function getReceiptSubtotal(): int
    {
        return collect($this->getReceiptItems())->sum('sub_total');
    }

    /**
     * Get the total value of this contract.
     */
    public function getReceiptTotal(): int
    {
        $items = collect($this->getReceiptItems());
        $itemsTotal = $items->sum('sub_total') + $items->sum('applied_tax');
        $contractTotal = $this->total_value ?? 0;

        return $contractTotal !== $itemsTotal ? $contractTotal : $itemsTotal;
    }

    /**
     * Check if this contract can generate a receipt.
     */
    public function canGenerateReceipt(): bool
    {
        return $this->id && $this->total_value > 0 && $this->details->count() > 0;
    }
}
