<?php

namespace App\Models;

use App\Contracts\Receipable;
use App\Enums\PaymentStatus;
use Carbon\Carbon;
use Database\Factories\PurchaseFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Purchase extends Model implements Receipable
{
    /** @use HasFactory<PurchaseFactory> */
    use HasFactory, SoftDeletes;

    /**
     * Cache for receipt items to avoid redundant calculations during a single request lifecycle.
     */
    private ?array $receiptItemsCache = null;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'user_id',
        'supplier_id',
        'invoice_number',
        'payment_status',
        'date',
        'total',
        'notes',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected $casts = [
        'date' => 'datetime',
        'total' => 'integer',
        'payment_status' => PaymentStatus::class,
    ];

    /**
     * Relation: Generated by User.
     * A sale belongs to a single user who processed it.
     *
     * @return BelongsTo<User, Purchase>
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Relation: Supplier.
     * A purchase belongs to a single supplier.
     *
     * @return BelongsTo<Supplier, Purchase>
     */
    public function supplier(): BelongsTo
    {
        return $this->belongsTo(Supplier::class);
    }

    /**
     * Relation: Purchase Details.
     * A purchase has many purchase details associated with it.
     *
     * @return HasMany<PurchaseDetail>
     */
    public function details(): HasMany
    {
        return $this->hasMany(PurchaseDetail::class);
    }

    /**
     * Relation: Payments.
     * A purchase can have multiple payments associated with it.
     *
     * @return MorphMany<Payment>
     */
    public function payments(): MorphMany
    {
        return $this->morphMany(Payment::class, 'origin');
    }

    // ===== Receipable Interface Implementation =====

    /**
     * Get the receipt/invoice number for this purchase.
     */
    public function getReceiptNumber(): string
    {
        return $this->invoice_number ?? 'N/A';
    }

    /**
     * Get the date when this purchase occurred.
     */
    public function getReceiptDate(): Carbon
    {
        return $this->date ?? now();
    }

    /**
     * Get the total amount for this purchase.
     */
    public function getReceiptTotal(): int
    {
        return $this->total ?? 0;
    }

    /**
     * Get the purchase items with all necessary data.
     */
    public function getReceiptItems(): array
    {
        if ($this->receiptItemsCache !== null) {
            return $this->receiptItemsCache;
        }

        // Use relation mapping instead of manual looping for efficiency
        $this->receiptItemsCache = $this->details->map(fn ($detail) => [
            'name' => $detail->purchasable->name ?? 'N/A',
            'quantity' => $detail->quantity,
            'unit_price' => $detail->unit_price,
            'sub_total' => $detail->sub_total,
            'applied_tax' => 0,
        ])->toArray();

        return $this->receiptItemsCache;
    }

    /**
     * Get the payments associated with this purchase.
     */
    public function getReceiptPayments(): array
    {
        return $this->payments->map(fn ($payment) => [
            'amount' => $payment->amount,
            'method_label' => $payment->method->label(),
            'change_amount' => $payment->change_amount,
            'reference' => $payment->reference,
            'date' => $payment->created_at,
        ])->toArray();
    }

    /**
     * Get the purchase subtotal (before taxes).
     */
    public function getReceiptSubtotal(): int
    {
        return collect($this->getReceiptItems())->sum('sub_total');
    }

    /**
     * Get the total tax amount.
     */
    public function getReceiptTaxTotal(): int
    {
        // Since getReceiptItems already calculates the tax amount in 'applied_tax',
        // we just need to sum it up.
        return collect($this->getReceiptItems())->sum('applied_tax');
    }

    /**
     * Check if this purchase can generate a receipt.
     */
    public function canGenerateReceipt(): bool
    {
        return ! empty($this->invoice_number) && $this->details()->exists();
    }
}
