<?php

namespace App\Models;

use App\Contracts\Receipable;
use App\Enums\PaymentStatus;
use Carbon\Carbon;
use Database\Factories\SaleFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Sale extends Model implements Receipable
{
    /** @use HasFactory<SaleFactory> */
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'user_id',
        'invoice_number',
        'payment_status',
        'date',
        'total',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected $casts = [
        'date' => 'datetime',
        'total' => 'integer',
        'payment_status' => PaymentStatus::class,
    ];

    /**
     * Relation: Generated by User.
     * A sale belongs to a single user who processed it.
     *
     * @return BelongsTo<User, Sale>
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Relation: Sale Details.
     * A sale has many sale details associated with it.
     *
     * @return HasMany<SaleDetail>
     */
    public function saleDetails()
    {
        return $this->hasMany(SaleDetail::class);
    }

    /**
     * Relation: Payments.
     * A sale can have multiple payments (e.g., split payments).
     *
     * @return MorphMany<Payment>
     */
    public function payments(): MorphMany
    {
        return $this->morphMany(Payment::class, 'origin');
    }

    // ===== Receipable Interface Implementation =====

    /**
     * Get the receipt/invoice number for this sale.
     */
    public function getReceiptNumber(): string
    {
        return $this->invoice_number ?? 'N/A';
    }

    /**
     * Get the date when this sale occurred.
     */
    public function getReceiptDate(): Carbon
    {
        return $this->date ?? now();
    }

    /**
     * Get the total amount for this sale.
     */
    public function getReceiptTotal(): int
    {
        return $this->total ?? 0;
    }

    /**
     * Get the sale items with all necessary data.
     */
    public function getReceiptItems(): array
    {
        return $this->saleDetails->map(fn($detail) => [
            'name' => $detail->product?->name ?? "Producto #{$detail->product_id}",
            'quantity' => $detail->quantity,
            'unit_price' => $detail->unit_price,
            'sub_total' => $detail->sub_total,
            'applied_tax' => $detail->applied_tax,
        ])->toArray();
    }

    /**
    * Get the payments associated with this sale.
    */
    public function getReceiptPayments(): array
    {
        return $this->payments()->get()->map(fn($payment) => [
            'amount' => $payment->amount,
            'method_label' => $payment->method->label(),
            'change_amount' => $payment->change_amount,
            'reference' => $payment->reference,
            'date' => $payment->created_at,
        ])->toArray();
    }

    /**
     * Get the subtotal (before taxes).
     */
    public function getReceiptSubtotal(): int
    {
        return $this->saleDetails->sum('sub_total') ?? 0;
    }

    /**
     * Get the total tax amount.
     */
    public function getReceiptTaxTotal(): int
    {
        return collect($this->getReceiptItems())->reduce(function ($carry, $item) {
            $taxAmount = (int) round($item['sub_total'] * ($item['applied_tax'] / 100));

            return $carry + $taxAmount;
        }, 0);
    }

    /**
     * Check if this sale can generate a receipt.
     */
    public function canGenerateReceipt(): bool
    {
        return $this->invoice_number && $this->saleDetails->count() > 0;
    }
}
