<?php

namespace App\Models;

use App\Enums\PaymentStatus;
use Database\Factories\SaleFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\SoftDeletes;

class Sale extends Model
{
    /** @use HasFactory<SaleFactory> */
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'user_id',
        'invoice_number',
        'payment_status',
        'date',
        'total',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected $casts = [
        'date' => 'datetime',
        'total' => 'decimal:2',
        'payment_status' => PaymentStatus::class,
    ];

    /**
     * Relation: Generated by User.
     * A sale belongs to a single user who processed it.
     *
     * @return BelongsTo<User, Sale>
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Relation: Sale Details.
     * A sale has many sale details associated with it.
     *
     * @return HasMany<SaleDetail>
     */
    public function saleDetails()
    {
        return $this->hasMany(SaleDetail::class);
    }

    /**
    * Relation: Payment.
    * A sale has one payment associated with it through a polymorphic relationship.
    *
    * @return MorphOne<Payment>
    */
    public function payment(): MorphOne
    {
        return $this->morphOne(Payment::class, 'origin');
    }
}
