<?php

namespace App\Models;

use App\Casts\CostaRicaDatetime;
use App\Enums\PaymentStatus;
use Database\Factories\SaleFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\SoftDeletes;

class Sale extends Model
{
    /** @use HasFactory<SaleFactory> */
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'employee_id',
        'invoice_number',
        'payment_status',
        'date',
        'total',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected $casts = [
        'date' => 'datetime',
        'total' => 'decimal:2',
        'payment_status' => PaymentStatus::class,
        // 'created_at' => CostaRicaDatetime::class,
        // 'updated_at' => CostaRicaDatetime::class,
        // 'deleted_at' => CostaRicaDatetime::class,
    ];

    /**
     * Relation: Generated by Employee.
     * A sale belongs to a single employee who processed it.
     *
     * @return BelongsTo<Employee, Sale>
     */
    public function employee(): BelongsTo
    {
        return $this->belongsTo(Employee::class);
    }

    // RELATIONSHIPS FOR DETAILS AND PAYMENTS ARE LEFT FOR FUTURE IMPLEMENTATIONS, AS THE CORRESPONDING MODELS HAVE NOT BEEN DEFINED YET.
    // /**
    //  * Relation: Contains SaleDetails.
    //  * A sale has one or many details (the products sold).
    //  *
    //  * @return HasMany<SaleDetail, Sale>
    //  */
    // public function details(): HasMany
    // {
    //     // Nota: Asegúrate de que el modelo SaleDetail exista
    //     return $this->hasMany(SaleDetail::class);
    // }

    // /**
    //  * Relation: Payments.
    //  * A sale can receive one or multiple payments.
    //  *
    //  * @return HasMany<Payment, Sale>
    //  */
    // public function payments(): HasMany
    // {
    //     // Nota: Asegúrate de que el modelo Payment exista
    //     return $this->hasMany(Payment::class);
    // }

    public function payment(): MorphOne
    {
        return $this->morphOne(Payment::class, 'origin');
    }
}
