import { NewCrudDataTable } from '../../utils/datatables.js';
import { showUser } from "./show.js";

window.showUser = showUser; // Make globally accessible for inline onclick handlers

/**
 * Translate the Message if needed.
 *
 * Clarification: I am using this method to create the DataTables because,
 * although the Olivier’s way of creating DataTables is simpler, it has a major problem:
 * if there are too many records in the database, the page will take too long to load even
 * when working locally.
 *
 * To solve this problem, I am using the DataTable's built-in
 * Server-Side Rendering feature, along with the 'yajra/laravel-datatables' package so that,
 * via an AJAX request, the DataTable fetches paginated data generated by the
 * 'yajra/laravel-datatables' package.
 *
 * For this reason, the configuration of this DataTable
 * is a bit more complex than usual. Fortunately, this method is more efficient and scalable.
 *
 * For reference, you can check the UsersController@index method to see how the server-side
 * data is generated.
 */

// Ensure the DOM is fully loaded before initializing the DataTable
$(document).ready(() => {
    // Define columns for users table
    const columns = [
        { data: 'name', name: 'name' },
        { data: 'email', name: 'email' },
        { // Assuming roles is an array, and we want the first role's name
            data: 'roles.0.name',
            name: 'role',
            render: function(data, type, row) {
                // Try to find the role label from userRoles (passed from Blade)
                const role = userRoles.find(role => role.value === data);
                return role ? role.label : data; // Fallback to raw data if not found
            }
        },
        {
            data: 'created_at',
            name: 'created_at',
            render: function(data) {
                // Format the created_at date to a more readable format
                const date = new Date(data);
                const day = String(date.getDate()).padStart(2, '0');
                const month = date.toLocaleDateString('es-ES', { month: 'long' });
                const year = date.getFullYear();
                return `${day} de ${month} del ${year}`;
            }
        }
    ];

    // Define actions
	const actions = {
		show: { route: userShowRoute, func: showUser, tooltip: 'Ver detalles' },
		edit: { route: userEditRoute, tooltip: 'Editar usuario' },
		delete: {
			route: userDeleteRoute,
			disabledIf: (row) => row.roles[0].name === 'admin',
			disabledIfTooltip: 'No se puede eliminar un usuario con rol de administrador.',
			tooltip: 'Eliminar usuario'
		}
	};


	// Define custom buttons
    const customButtons = [
        {
            text: 'Registrar Asistencia',
            href: '#',
            class: 'btn-outline-info',
            icon: 'bi-card-checklist'
        },
        {
            text: 'Crear Usuario',
            href: userCreateRoute,
            class: 'btn-primary',
            icon: 'bi-person-plus-fill'
        }
    ];

    // Initialize the CRUD DataTable
    NewCrudDataTable('users-table', userRoute, columns, actions, customButtons);
});
